# Generated by Django 5.0.1 on 2024-02-01 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_book_bookid_alter_bookdetails_detailsid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookdetails',
            old_name='bookID',
            new_name='book',
        ),
    ]
